### ISSUE TITLE
Error kaptDebugKotlin when try build this repository

### ISSUE THREAD

**Issue by irfanirawansukirman** [DevAnuragGarg/MovieBox#3]
* What went wrong:
Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)

**Comment by DevAnuragGarg** [comment]
I don't see any error on my side. As I keep all the gradle dependencies, kotlin and gradle updated, you need to check if your android studio is also using the same versions. 
Kindly go through this link also: https://stackoverflow.com/questions/46850060/errorexecution-failed-for-task-appkaptdebugkotlin
Hope this will help. Closing issue now.
